### ISSUE TITLE
IdekCTF - Coffe Shop

### ISSUE THREAD

**Issue by GonTanaka** [junron/public-writeups#1]
Hi junron,

thank you for your writeup.
Can I ask you where did you find the libc-2.31.so file? Because it was not provided with this challenge.
To follow your code I patched the libc-2.31.so from the one provided with the Vanity_check_I challenge.

**Comment by junron** [comment]
I guessed that the libc version would be the same across all the challenges. It might be possible to leak the libc version by tricking malloc into returning a chunk pointing to the GOT and reading that chunk.

**Comment by GonTanaka** [comment]
Thank you Junron.
